### test 接口
GET http://localhost:8000/user/test


### 测试 查询用户数量 - 经过网关
GET http://localhost:8000/user/count

### 测试 查询用户数量 - 不经过网关
GET http://localhost:8081/count

### 测试 用户注册
POST http://localhost:8000/user/register
Content-Type: application/json
Accept-Language: en

{
  "mobile": ""
}

### 测试 用户发送验证码
POST http://localhost:8000/user/send-code
Content-Type: application/json
Accept-Language: en

{
  "mobile": "15980768901"
}

### 测试 用户登录 - 用户不存在
POST http://localhost:8000/user/login
Content-Type: application/json
Accept-Language: en

{
  "mobile": "15980768900"
}

### 测试 用户登录 - 用户不存在 - 发送验证码
POST http://localhost:8000/user/send-code
Content-Type: application/json
Accept-Language: en

{
  "mobile": "15980768900"
}

### 测试 用户登录 - 验证码错误
POST http://localhost:8000/user/login
Content-Type: application/json
Accept-Language: en

{
  "mobile": "15980768900",
  "code": "1234"
}

### 测试 用户登录 - 验证码正确
POST http://localhost:8000/user/login
Content-Type: application/json
Accept-Language: en

{
  "mobile": "15980768900",
  "code": "6666"
}