server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cr_test?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: root