spring:
  profiles:
    active: dev


  datasource:
    url: jdbc:mysql://localhost:3306/数据库名?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: 数据库用户密码

# 配置 MyBatis 映射文件的路径，支持通配符“**”匹配多级目录下的所有 XML 文件
mybatis:
  mapper-locations: classpath:mapper/**/*.xml
