spring:
  profiles:
    active: dev

  datasource:
    url: jdbc:mysql://localhost:3306/数据库名?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: 数据库用户密码